apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: wordpress-openshift

---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: wordpress-openshift
spec:
  source:
    dockerfile: |
      FROM wordpress:latest

      RUN sed -i 's/Listen 80/Listen 8080/' /etc/apache2/ports.conf && \
          sed -i 's/<VirtualHost \*:80>/<VirtualHost *:8080>/' /etc/apache2/sites-available/000-default.conf

      EXPOSE 8080
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: docker.io/library/wordpress:latest
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-openshift:latest
